<img style="float: left;;" src='Figures/alinco.png' /></a>

# <center> <font color= #000047> Actividad 1: Preprocesamiento y EDA </font>
___

        

### Considere el dataframe que se encuentra en "Airbn_Data.csv", cargue el dataframe (pd.read_csv()) y realice lo que se pide:

In [5]:
import pandas as pd
import numpy as np
from HAIA import HyAIA as hy

In [6]:
airbnb_df = pd.read_csv('Data/Airbnb_Data_sample.csv', index_col=[0])
airbnb_df.head()

id                                              NAME  \
4       1003689  Entire Apt: Spacious Studio/Loft by central park   
72587  41091136                  Central Park west. Big Cozy Room   
21781  13030982              ❤ of Manhattan | Fantastic 1 Bedroom   
45621  26197814           阳台大双人房 (queens size room with balcony )   
24727  14658058  Cozy, Bright, Bohemian Space in the East Village   

           host id host_identity_verified host name neighbourhood group  \
4      92037596077               verified    Lyndon           Manhattan   
72587  19388079471            unconfirmed  Fernando           Manhattan   
21781  43427426473            unconfirmed      Kyle           Manhattan   
45621  27298749852            unconfirmed        Li              Queens   
24727  49124834493               verified   Michael           Manhattan   

          neighbourhood       lat      long        country  ... service fee  \
4           East Harlem  40.79851 -73.94399  United States  ...        $41    
72587   Upper West Side  40.79927 -73.96235  United States  ...       $142    
21781  Theater District  40.76321 -73.98356  United States  ...       $196    
45621          Flushing  40.76316 -73.80869  United States  ...       $205    
24727      East Village  40.73022 -73.98623  United States  ...        $62    

      minimum nights number of reviews last review  reviews per month  \
4               10.0               9.0  11/19/2018               0.10   
72587            1.0              87.0   6/22/2019               1.88   
21781           30.0               0.0         NaN                NaN   
45621            1.0               0.0         NaN                NaN   
24727            5.0               2.0   8/27/2017               0.08   

      review rate number calculated host listings count  availability 365  \
4                    3.0                            1.0             289.0   
72587                4.0                            2.0             263.0   
21781                4.0                           23.0             364.0   
45621                2.0                            7.0             329.0   
24727                3.0                            1.0               0.0   

                                             house_rules license  
4      Please no smoking in the house, porch or on th...     NaN  
72587                                                NaN     NaN  
21781  We live on the 3rd floor of a 3-family house, ...     NaN  
45621  There is  light breakfast - cereal with milk t...     NaN  
24727                                                NaN     NaN  

[5 rows x 26 columns]

<hr>   

> Realizar un reporte de calidad de datos y comente sus resultados.


In [7]:
airbnb = hy(airbnb_df)

In [9]:
airbnb.dqr.head()

Columns_Names  Dtypes  Present_values  \
id                                          id   int64            5131   
NAME                                      NAME  object            5121   
host id                                host id   int64            5131   
host_identity_verified  host_identity_verified  object            5117   
host name                            host name  object            5113   

                        Missing_values  Unique_values   Max_values Min_values  \
id                                   0           5130     57360237    1003689   
NAME                                10           4970          N/A        N/A   
host id                              0           5130  98755572183  129756565   
host_identity_verified              14              2          N/A        N/A   
host name                           18           2547          N/A        N/A   

                               Mean_values  Is_Categorical  
id                         29251442.863769           False  
NAME                                   N/A            True  
host id                 49903697843.349251           False  
host_identity_verified                 N/A            True  
host name                              N/A            True

> Mostrar las columnas categóricas ordinales, mostrar las columnas categóricas nominales, Mostrar las columnas continuas, Mostrar las columnas binarias.


In [12]:
airbnb.dqr.shape

(26, 9)

In [13]:
#Columnas Continuas
airbnb.cuantitativos_columns, len(airbnb.cuantitativos_columns)


(Index(['id', 'host id', 'lat', 'long', 'Construction year', 'minimum nights',
        'number of reviews', 'reviews per month', 'review rate number',
        'calculated host listings count', 'availability 365', 'license'],
       dtype='object'),
 12)

In [14]:
#Columnas Binarias
airbnb.binarios_columns, len(airbnb.binarios_columns)

(['host_identity_verified', 'instant_bookable'], 2)

In [15]:
#Columnas Categóricas
airbnb.categoricos_columns, len(airbnb.categoricos_columns)

(['NAME',
  'host name',
  'neighbourhood group',
  'neighbourhood',
  'cancellation_policy',
  'room type',
  'price',
  'service fee',
  'last review',
  'house_rules'],
 10)

In [16]:
airbnb.data_categoricos.head(3)

NAME host name  \
4      Entire Apt: Spacious Studio/Loft by central park    Lyndon   
72587                  Central Park west. Big Cozy Room  Fernando   
21781              ❤ of Manhattan | Fantastic 1 Bedroom      Kyle   

      neighbourhood group     neighbourhood cancellation_policy  \
4               Manhattan       East Harlem            moderate   
72587           Manhattan   Upper West Side            moderate   
21781           Manhattan  Theater District            moderate   

             room type  price service fee last review  \
4      Entire home/apt  $204         $41   11/19/2018   
72587     Private room  $709        $142    6/22/2019   
21781  Entire home/apt  $981        $196          NaN   

                                             house_rules  
4      Please no smoking in the house, porch or on th...  
72587                                                NaN  
21781  We live on the 3rd floor of a 3-family house, ...

In [17]:
airbnb.categoricos_columns

['NAME',
 'host name',
 'neighbourhood group',
 'neighbourhood',
 'cancellation_policy',
 'room type',
 'price',
 'service fee',
 'last review',
 'house_rules']

In [19]:
#Categóricos Ordinales?
col_ord = ['last review', 'cancellation_policy']
#price y service fee pueden convertirse en datos continuos 

In [20]:
#Categóricos Nominales?
col_nom = list(set(airbnb.categoricos_columns) - set(col_ord))

['NAME',
 'neighbourhood',
 'room type',
 'price',
 'house_rules',
 'host name',
 'service fee',
 'neighbourhood group']

> Usando el reporte de calidad de datos obtenido, realizar una limpieza de datos, dejar sólo en el data frame las columnas que contengan el 80% o más de valores presentes. Rellenar los datos "NaN" (missing) según el tipo de dato (categoricos --> unk, continuos --> promedio).


In [24]:
#Porcentaje de valores presentes
airbnb.dqr['%Present_values'] = airbnb.dqr['Present_values']/len(airbnb.data)

In [29]:
#columnas que tienen más del 80% de valores presentes
col80=airbnb.dqr[airbnb.dqr['%Present_values']>0.8].index.to_list()


In [33]:
#Filtro de las columnas con el 80% de valores presentes
airbnb.data = airbnb.data[col80]
airbnb.data.head(2)

id                                              NAME  \
4       1003689  Entire Apt: Spacious Studio/Loft by central park   
72587  41091136                  Central Park west. Big Cozy Room   

           host id host_identity_verified host name neighbourhood group  \
4      92037596077               verified    Lyndon           Manhattan   
72587  19388079471            unconfirmed  Fernando           Manhattan   

         neighbourhood       lat      long        country  ...  \
4          East Harlem  40.79851 -73.94399  United States  ...   
72587  Upper West Side  40.79927 -73.96235  United States  ...   

      Construction year  price service fee minimum nights  number of reviews  \
4                2009.0  $204         $41            10.0                9.0   
72587            2012.0  $709        $142             1.0               87.0   

      last review reviews per month  review rate number  \
4      11/19/2018              0.10                 3.0   
72587   6/22/2019              1.88                 4.0   

       calculated host listings count availability 365  
4                                 1.0            289.0  
72587                             2.0            263.0  

[2 rows x 24 columns]

In [38]:
#Rellenar datos missing para categóricos con 'unk' (desconocido)
_,col_cat = airbnb.get_categoricos()
for col in col_cat:
    airbnb.data[col].fillna('unk', inplace = True)

In [41]:
#Rellenar datos missing para continuos con el promedio
_,col_cont = airbnb.get_cuantitativos()
for col in col_cont:
    airbnb.data[col].fillna(airbnb.data[col].mean(), inplace=True)

In [42]:
airbnb.dqr = airbnb.get_dqr()
airbnb.dqr 

Columns_Names   Dtypes  \
id                                                          id    int64   
NAME                                                      NAME   object   
host id                                                host id    int64   
host_identity_verified                  host_identity_verified   object   
host name                                            host name   object   
neighbourhood group                        neighbourhood group   object   
neighbourhood                                    neighbourhood   object   
lat                                                        lat  float64   
long                                                      long  float64   
country                                                country   object   
country code                                      country code   object   
instant_bookable                              instant_bookable   object   
cancellation_policy                        cancellation_policy   object   
room type                                            room type   object   
Construction year                            Construction year  float64   
price                                                    price   object   
service fee                                        service fee   object   
minimum nights                                  minimum nights  float64   
number of reviews                            number of reviews  float64   
last review                                        last review   object   
reviews per month                            reviews per month  float64   
review rate number                          review rate number  float64   
calculated host listings count  calculated host listings count  float64   
availability 365                              availability 365  float64   

                                Present_values  Missing_values  Unique_values  \
id                                        5131               0           5130   
NAME                                      5131               0           4971   
host id                                   5131               0           5130   
host_identity_verified                    5117              14              2   
host name                                 5131               0           2548   
neighbourhood group                       5131               0              6   
neighbourhood                             5131               0            193   
lat                                       5131               0           4410   
long                                      5131               0           4117   
country                                   5110              21              1   
country code                              5126               5              1   
instant_bookable                          5126               5              2   
cancellation_policy                       5131               0              4   
room type                                 5131               0              4   
Construction year                         5131               0             21   
price                                     5131               0           1134   
service fee                               5131               0            232   
minimum nights                            5131               0             57   
number of reviews                         5131               0            255   
last review                               5131               0           1142   
reviews per month                         5131               0            588   
review rate number                        5131               0              6   
calculated host listings count            5131               0             77   
availability 365                          5131               0            433   

                                                                       Max_values  \
id                                                            


> Realizar una limpieza de datos en las columnas:

> Eliminar la columna "license"

> La columna **"service fee"** contiene un caracter de símbolo de pesos qué se encuentra antes del valor numérico, esto hace que esta columna se considere como 'Object'. Esta columna deberá de ser una columna continua. Realizar una limpieza eliminando el caracter de pesos y convertirlo a un dato continuo. **Hint:** realizar un [cast](https://thedataschools.com/python/casting/)(float)

> La columna **"last review"** debe de tener el formato : **xx/xx/xxxx, ejemplo 7/5/2019 ----> 07/05/2019**, realizar una función para ralizar esta conversión y aplicar esta función a la columna "last review" (**Hint:** utilice el método apply()).

> La columna **"NAME"** debe de estar en Minúsculas, cambiar el caracter '&' por ' and '

> La columna **"host id"** debe de contener 11 dígitos, cualquier muestra que contenga más o menos de 11 dígitos será una muestra invalida y se tendrá que eliminar.



In [46]:
#Con el filtro del 80% de los valores presentes la columna license ya no se toma en cuenta
airbnb.data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365'],
      dtype='object')

In [56]:
airbnb.data['service fee'] = airbnb.data['service fee'].apply(airbnb.replace_text, args=('$',''))
airbnb.data['price'] = airbnb.data['price'].apply(airbnb.replace_text, args=('$','')).apply(airbnb.remove_whitespace).apply(airbnb.replace_text, args=(',','.')).apply(airbnb.replace_text, args=('unk','0.0'))

In [57]:
airbnb.data['price'].astype(float)

4        204.000
72587    709.000
21781    981.000
45621      1.026
24727    310.000
          ...   
43075    697.000
28175    569.000
40133    609.000
70608    167.000
2938       1.167
Name: price, Length: 5131, dtype: float64

> Obtener 5 insights de los datos después de haber hecho la limpieza: 

> ¿Cuál es el rango de tiempo que cubre el dataset?

> ¿Cuántos países diferentes se toman en cuenta en el dataset?

> ¿Cuál es la distribución de salarios en el dataset por 'neighbourhood group'?

> ¿Qué vecindario ('neighbourhood group') tiene el mayor número de hosts?

> ¿Cuáles y cuántos son los diferentes tipos de cuartos disponibles en el dataset?
 

In [59]:
#Sólo se toma en cuenta 1 país
airbnb.data['country'].unique()

array(['United States', nan], dtype=object)

In [63]:
airbnb.data.groupby(by=['neighbourhood group'])['price'].value_counts()

neighbourhood group  price
Bronx                1.090    2
                     139      2
                     148      2
                     654      2
                     701      2
                             ..
Staten Island        984      1
                     99       1
unk                  266      1
                     618      1
                     925      1
Name: price, Length: 2591, dtype: int64

In [85]:
airbnb.data.groupby(by=['neighbourhood group'])['price'].value_counts()

neighbourhood group  price
Bronx                1.090    2
                     139      2
                     148      2
                     654      2
                     701      2
                             ..
Staten Island        984      1
                     99       1
unk                  266      1
                     618      1
                     925      1
Name: price, Length: 2591, dtype: int64


> Filtre el datasete que se obtenga del procedimiento anterior} con las siguientes columnas: **host id','lat', 'long', 'Construction year', 'service fee', 'reviews per month', 'review rate number','availability 365']**. Aplicar el método **set_index** a la columna 'host id' de tal forma que el indice del dataframe sea 'host_id'. Apartir del dataset obtenido, cree una matriz de similitud por distancia euclideana estandarizada.


In [66]:
airbnb_filtro = airbnb.data[['host id','lat', 'long', 'Construction year', 'service fee', 'reviews per month', 'review rate number','availability 365']]
airbnb_filtro.set_index('host id', inplace=True)

In [67]:
airbnb_filtro

lat      long  Construction year service fee  \
host id                                                          
92037596077  40.79851 -73.94399             2009.0         41    
19388079471  40.79927 -73.96235             2012.0        142    
43427426473  40.76321 -73.98356             2007.0        196    
27298749852  40.76316 -73.80869             2006.0        205    
49124834493  40.73022 -73.98623             2014.0         62    
...               ...       ...                ...         ...   
42820982123  40.68727 -73.86413             2016.0        139    
37971970127  40.80485 -73.96345             2005.0        114    
11523190081  40.72176 -73.99218             2019.0        122    
12517661682  40.75099 -73.96994             2004.0         33    
23479231166  40.71380 -73.96251             2014.0        233    

             reviews per month  review rate number  availability 365  
host id                                                               
92037596077           0.100000                 3.0             289.0  
19388079471           1.880000                 4.0             263.0  
43427426473           1.365414                 4.0             364.0  
27298749852           1.365414                 2.0             329.0  
49124834493           0.080000                 3.0               0.0  
...                        ...                 ...               ...  
42820982123           1.880000                 3.0             361.0  
37971970127           0.050000                 3.0               0.0  
11523190081           2.920000                 4.0              16.0  
12517661682           0.100000                 4.0             358.0  
23479231166           3.370000                 3.0              63.0  

[5131 rows x 7 columns]

In [68]:
import gower

In [70]:
def MatSim_Gower(df):
    M_Sim = pd.DataFrame(gower.gower_matrix(df), 
                     index = df.index.to_list(), columns=df.index.to_list())
    return M_Sim

In [71]:
mat_airbnb = MatSim_Gower(airbnb_filtro)

In [72]:
mat_airbnb

92037596077  19388079471  43427426473  27298749852  49124834493  \
92037596077     0.000000     0.207010     0.205181     0.183536     0.204845   
19388079471     0.207010     0.000000     0.194462     0.233571     0.232544   
43427426473     0.205181     0.194462     0.000000     0.172349     0.263956   
27298749852     0.183536     0.233571     0.172349     0.000000     0.219269   
49124834493     0.204845     0.232544     0.263956     0.219269     0.000000   
...                  ...          ...          ...          ...          ...   
42820982123     0.226305     0.225486     0.242713     0.269937     0.162385   
37971970127     0.181110     0.253357     0.224672     0.176675     0.231787   
11523190081     0.294564     0.230976     0.268129     0.294871     0.234040   
12517661682     0.228943     0.232342     0.173284     0.195154     0.270724   
23479231166     0.233525     0.241365     0.266281     0.233831     0.162854   

             36496408362  16404691633  38598542895  81572634865  66472440856  \
92037596077     0.272213     0.308450     0.269967     0.282897     0.252673   
19388079471     0.298463     0.317298     0.225456     0.304013     0.189085   
43427426473     0.320813     0.353443     0.256868     0.335391     0.225860   
27298749852     0.218513     0.237328     0.283610     0.219310     0.252979   
49124834493     0.222664     0.267073     0.209717     0.233042     0.232727   
...                  ...          ...          ...          ...          ...   
42820982123     0.227447     0.207767     0.198165     0.215648     0.234103   
37971970127     0.296732     0.357008     0.297132     0.311690     0.279838   
11523190081     0.238659     0.243860     0.168695     0.240991     0.220797   
12517661682     0.344575     0.374329     0.264417     0.348776     0.247123   
23479231166     0.256451     0.238199     0.228710     0.246192     0.217949   

             ...  50601891157  28883233453  1779050175   4916045085   \
92037596077  ...     0.208257     0.209446     0.264637     0.214640   
19388079471  ...     0.279000     0.202170     0.200418     0.256919   
43427426473  ...     0.227125     0.168698     0.219500     0.236629   
27298749852  ...     0.111880     0.237076     0.264943     0.225335   
49124834493  ...     0.256099     0.220714     0.226491     0.212653   
...          ...          ...          ...          ...          ...   
42820982123  ...     0.271191     0.231145     0.206235     0.211398   
37971970127  ...     0.207652     0.247699     0.298588     0.239638   
11523190081  ...     0.346041     0.232721     0.224381     0.264628   
12517661682  ...     0.235850     0.183461     0.248303     0.265433   
23479231166  ...     0.285002     0.237199     0.228858     0.192657   

             54939997019  42820982123  37971970127  11523190081  12517661682  \
92037596077     0.295208     0.226305     0.181110     0.294564     0.228943   
19388079471     0.296591     0.225486     0.253357     0.230976     0.232342   
43427426473     0.241322     0.242713     0.224672     0.268129     0.173284   
27298749852     0.264519     0.269937     0.176675     0.294871     0.195154   
49124834493     0.308307     0.162385     0.231787     0.234040     0.270724   
...                  ...          ...          ...          ...          ...   
42820982123     0.296036     0.000000     0.264557     0.195887     0.271749   
37971970127     0.274609     0.264557     0.000000     0.322969     0.218359   
11523190081     0.320538     0.195887     0.322969     0.000000     0.289015   
12517661682     0.210895     0.271749     0.218359     0.289015     0.000000   
23479231166     0.324271     0.159011     0.265027     0.214829     0.295084   

             23479231166  
92037596077     0.233525  
19388079471     0.241365  
43427426473     0.266281  
27298749852     0.233831  
49124834493     0.162854  
...                  ...  
42820982123     0.159011  
37971970127     0.265027  
11523190081     0.2148

>Obtenga el top 5 de **'host_id'** más parecidas al **'host_id' = '92037596077'**
 


In [86]:
mat_airbnb.loc[92037596077].sort_values().index[1:6]

Int64Index([47325377422, 38081580137, 46849146306, 6691802978, 22013707279], dtype='int64')